ports/esp32/boards/M5CORE2: board support for M5Stack Core2
lvgl/lv_micropython pull request #27
Opened 2021-05-27 17:25 UTC by ropg

I know the M5Stack Core2's UIFlow thing is really just LVGL and micropython, but that's sort of hidden behind tons of obfuscated Javascript and cloud-based connecting the the devices. Here's a pure python setup where inisetup.py creates working boot.py and main.py for a simple one-button example in the flash filesystem. Self-written pure-python AXP192 support and the derived m5core2_power libraries included.

The power library and it's documentation will grow, but this will get people started and is a working setup.

2021-05-27 20:42 UTC, amirgon requested changes
Thank you for your contribution!

Some general questions:
- Are your drivers (axp192, ft6x36, m5core2_power) based on some existing codebase?  
If you wrote them yourself based on the datasheet - no problem.  
But if they are based on some other code - need to mention this in the comments and make sure that the license of the other code is compatible with MIT license
- Are all your drivers (axp192, ft6x36, m5core2_power) specific to m5? If these are IC drivers they should be under lv_micropython_bindings under "drivers" dir. I've used soft links in order to freeze drivers from lv_micropython_bindings/drivers/esp32 into [esp32/modules](https://github.com/lvgl/lv_micropython/tree/master/ports/esp32/modules).  
Even if these are M5 specific drivers, I still think it makes more sense to put them under lv_micropython_bindings because some people are not using lv_micropython but has their own Micropython fork. These people still use lv_micropython_bindings as a submodule of their fork so if you put your drivers there they would be available to them too.
- Specifically about FT6X36, you already [opened a PR](https://github.com/lvgl/lv_binding_micropython/pull/140) to add it to lv_micropython_bindings. It's better to prevent code duplication and avoid the same driver on two locations.

2021-05-27 20:42 UTC, amirgon commented on ports/esp32/boards/M5CORE2/README.md
> +
This is no longer true on latest Micropython, which uses CMake on ESP32 and can work with (almost) any ESP-IDF commit.  
See `dev` and `dev-8` branches which use latest Micropython.  
`dev-8` will soon become `master` and current `master` will become `release/v7`.

2021-05-27 20:49 UTC, ropg commented on ports/esp32/boards/M5CORE2/README.md
> +
Ah, cool!

2021-05-27 21:02 UTC, ropg commented
ft6x36 driver is completely mine. Some of my axp192 code is new, other parts loosely based on two existing implementations, both MIT I believe. I have indeed not yet added any credits or even my own authorship. Will check and do so tomorrow.

As for ft6x36 being in to locations: true. AXP192 is a chip driver, m5core2_power depends on it and is M5Core2 specific. But yes, the AXP192 can be in drivers. I didn't know what the policy is there, because it's nothing to do with graphics / LVGL. I'll revise everything tomorrow. And play with the dev and dev-8 branches a bit.

2021-05-28 12:15 UTC, ropg commented on ports/esp32/boards/M5CORE2/README.md
> +
Does this mean I should be submitting  to one of these branches instead to have things be available there, or will they be merged automatically?

2021-05-28 20:43 UTC, amirgon commented
> m5core2_power is written by me again. We'll keep it with the board files? In that case I will modify this commit when the other two are merged.

I guess we could put it with the board files on lv_micropython.  
Another option is adding an "m5" dir under drivers on lv_binding_micropython, but for a specific single driver I'm not sure it's necessary.

After all drivers are added to lv_binding_micropython upstream, please pull and update the lv_binding_micropython submodule version in this PR.

2021-05-28 20:47 UTC, amirgon commented on ports/esp32/boards/M5CORE2/README.md
> +
When I'll prepare dev-8 branch, I'll first merge master into it, and only then merge it back to master.
I hope I won't have too many issues with that.  

This way we'll have your changes on both v7 and v8.
We might need your help testing your code on v8 after doing that, because I don't have M5 hardware.

2021-05-28 20:54 UTC, ropg commented on ports/esp32/boards/M5CORE2/README.md
> +
Sure, glad to help. I recommend getting one though: fun little device...

2021-05-29 08:26 UTC, closed without merging

2021-05-29 19:16 UTC, amirgon commented
@ropg Why did you close this?

2021-05-30 12:10 UTC, ropg commented
It was a side-effect of me being very frustrated with being unable to get my github fork in the same state as the one at lvgl that I deleted it and started over, not thinking there was a PR depending on it. I will refile. when I'm done...

Have another question. In v8 the names of INDEV_STATE.REL and PR changed to RELEASED and PRESSED. This means changes to the ft6x36 and minimal example driver in dev-8.0. How is that best done: shall I just submit a PR with those two submits but slightly different file contents to the dev-8.0 branch? Or do I cherry-pick those commits and then PR with those and new commits for the changes?