RPi Pico port
lvgl/lv_micropython pull request #42
Opened 2021-08-31 05:23 UTC by eudoxos

based on work of @jgpeiro
https://forum.lvgl.io/t/build-lvgl-for-raspberry-pi-pico/5543 . Runtime functionality not verified yet.

2021-08-31 05:26 UTC, eudoxos commented
This is complemented by the following submodule PRs:

* https://github.com/lvgl/lv_binding_micropython/pull/174
* https://github.com/lvgl/lvgl/pull/2512

2021-08-31 20:33 UTC, amirgon requested changes
Hi @eudoxos , thank you and @jgpeiro for this contribution!

See my comments below.

To make progress, you would also have to test this on a RPi Pico device and make sure you didn't break other ports (such as the ESP32).

2021-08-31 20:33 UTC, amirgon commented on ports/rp2/CMakeLists.txt
> +include(${MICROPY_DIR}/lib/lv_bindings/mkrules.cmake)
You may need to wrap this in `if(NOT CMAKE_BUILD_EARLY_EXPANSION)` like done here:

https://github.com/lvgl/lv_micropython/blob/e71a9729cc9418b15034ea14d2aab1ba027aa0ef/ports/esp32/main/CMakeLists.txt#L78-L80

2021-08-31 20:33 UTC, amirgon commented on ports/rp2/CMakeLists.txt
> +# set(MICROPY_SOURCE_LVGL_GEN
Please remove these commented out lines you added.

2021-08-31 20:33 UTC, amirgon commented on ports/rp2/CMakeLists.txt
> +include_directories(
These directories `${LV_BINDINGS_DIR}/scr/...` don't really exist...

2021-08-31 20:33 UTC, amirgon commented on ports/rp2/CMakeLists.txt
> +file(GLOB_RECURSE MICROPY_SOURCE_LVGL ${MICROPY_DIR}/lib/lv_bindings/lvgl/src/*.c)
This is not the correct way to do it.
LVGL has it's [own CMake file](https://github.com/lvgl/lvgl/blob/master/CMakeLists.txt), please add it as a module like this:

https://github.com/lvgl/lv_micropython/blob/e71a9729cc9418b15034ea14d2aab1ba027aa0ef/ports/esp32/CMakeLists.txt#L42

2021-09-01 04:43 UTC, eudoxos commented on ports/rp2/CMakeLists.txt
> +include(${MICROPY_DIR}/lib/lv_bindings/mkrules.cmake)
done.

2021-09-01 04:51 UTC, eudoxos commented on ports/rp2/CMakeLists.txt
> +file(GLOB_RECURSE MICROPY_SOURCE_LVGL ${MICROPY_DIR}/lib/lv_bindings/lvgl/src/*.c)
`idf_build_component` is ESP-specific, most of that CMake file is guarded with `ESP_PLATFORM` and otherwise reduces to:
```cmake
file(GLOB_RECURSE EXAMPLE_SOURCES ${CMAKE_CURRENT_LIST_DIR}/examples/*.c)
add_library(lvgl_examples STATIC ${EXAMPLE_SOURCES})
```
It declares the static library (but won't pass it anything related to Micropython (such as its include directories) so it won't even compile when included with `add_subdirectory(${MICROPY_DIR}/liv/lv_bindings/lvgl ${CMAKE_BINARY_DIR}/lvgl)`. 

If you see something I'm missing, I will be happy to hear that.

2021-09-01 06:01 UTC, amirgon commented on ports/rp2/CMakeLists.txt
> +file(GLOB_RECURSE MICROPY_SOURCE_LVGL ${MICROPY_DIR}/lib/lv_bindings/lvgl/src/*.c)
Today LVGL CMake is really reduced to these two lines, but in the future LVGL CMake script may become more complex, have RPi specific build rules etc.  

I think it makes sense to keep the logic of building LVGL code in LVGL, as much as possible.  
Otherwise every change in LVGL's CMake would require a change in RPi CMake and that's harder to maintain.

When building LVGL on ESP32+Micropython we added a dependency on Micropython's "main" in order to pass include directories:
```cmake
if (LV_MICROPYTHON)
    idf_component_register(SRCS ${SOURCES}
                           INCLUDE_DIRS . src ../
                           REQUIRES main)
else()
```

I think you can do something like this for RPi with pure CMake.

2021-09-01 07:33 UTC, eudoxos commented on ports/rp2/CMakeLists.txt
> +file(GLOB_RECURSE MICROPY_SOURCE_LVGL ${MICROPY_DIR}/lib/lv_bindings/lvgl/src/*.c)
Okay, I tried a bit but it looks quite difficult: LVGL needs to use all the compiler flags and include directories as micropython, but it can't link to the micropython target itself (because it is linked to it, and because it is an executable), and the various options are many (pico-sdk headers, compile definitions, and so on and so forth). I will see if those could be copied from the `${MICROPY_TARGET}` target somehow, but so far did not succeed (I asked about copying properties [at SO](https://stackoverflow.com/q/69008931/761090)).

Maybe the LVGL CMakeLists.txt could just set `LVGL_SRCS` with `EXPORT_PARENT`? This way the fllie globbing would be done in lvgl but the buildling part as part of Micropython.

2021-09-01 08:16 UTC, amirgon commented on ports/rp2/CMakeLists.txt
> +file(GLOB_RECURSE MICROPY_SOURCE_LVGL ${MICROPY_DIR}/lib/lv_bindings/lvgl/src/*.c)
> Maybe the LVGL CMakeLists.txt could just set `LVGL_SRCS` with `EXPORT_PARENT`? This way the fllie globbing would be done in lvgl but the buildling part as part of Micropython.

That's possible, but what if in the future LVGL CMake script targets RPi (without Micropython) and specifies some RPi specific compiler options etc.?  

I'm not too proficient with CMake, but isn't there a way to tell it about a dependency and let it handle include paths, compiler flags etc. automatically?  
This seems to be working for ESP32 by adding `REQUIRES main` so I wonder if something like this could be done for RPi with pure CMake.

2021-09-01 09:43 UTC, eudoxos commented on ports/rp2/CMakeLists.txt
> +file(GLOB_RECURSE MICROPY_SOURCE_LVGL ${MICROPY_DIR}/lib/lv_bindings/lvgl/src/*.c)
So with these
```cmake
    target_compile_definitions(lvgl PUBLIC $<TARGET_PROPERTY:${MICROPY_TARGET},COMPILE_DEFINITIONS>)
    target_compile_options(lvgl PUBLIC $<TARGET_PROPERTY:${MICROPY_TARGET},COMPILE_OPTIONS>)
    target_include_directories(lvgl PUBLIC $<TARGET_PROPERTY:${MICROPY_TARGET},INCLUDE_DIRECTORIES>)
```
lvgl would almost compile, but it does not have declared dependency on `genhdr/qstrdefs.generated.h` (which is generated with micropython) so it might fail to compile depending on the order of compilation. Not good.

It seems that `idf_component_register` passes all necessary platform flags and such.

2021-09-02 08:27 UTC, amirgon commented on ports/rp2/CMakeLists.txt
> +file(GLOB_RECURSE MICROPY_SOURCE_LVGL ${MICROPY_DIR}/lib/lv_bindings/lvgl/src/*.c)
> The trick was to simply add LVGL source to micropython using `target_sources(${MICROPY_TARGET} PRIVATE ...)` which appends those source files to those already defined for `${MICROPY_TARGET}`.

What would happen if LVGL's `CMakeLists.txt` ever adds RPi specific definitions, compilation flags etc.?
Would they be propagated somehow by `target_sources`?

I understand there is a challenge here, but ideally I think it would make more sense to build LVGL as a library instead of building it as part of Micropython sources.  
This looks like the common practice - looking at [rp2/CMakeLists.txt](https://github.com/micropython/micropython/blob/master/ports/rp2/CMakeLists.txt), I can see it calls `target_link_libraries` for different components (sdk components, usermod)

2021-09-03 05:19 UTC, eudoxos commented on ports/rp2/CMakeLists.txt
> +file(GLOB_RECURSE MICROPY_SOURCE_LVGL ${MICROPY_DIR}/lib/lv_bindings/lvgl/src/*.c)
I got some progress, it looks good. The trick was to [read Micropython docs](https://micropython-usermod.readthedocs.io/en/latest/usermods_05.html) on compiling 3rd-party modules.

The whole thing works like this:

1. Don't touch micropython's port CMakeLists.txt, nor anything else. It is not needed at all.
2. Compile the port as `make USER_C_MODULES=../../lib/lv_bindings/mkrules.cmake`
3. Declare the compiled module as `INTERFACE` module and make `usermod` target depend on it. The beauty of `INTERFACE` targets is that they inherit all compile options from the target they depend on (`usermod` in this case).

Now, the `mkrules.cmake` needs to add something like this (this is tested and works):

```cmake
# create targets for generated files
all_lv_bindings()

# bindings target (the mpy module)
add_library(usermod_lv_bindings INTERFACE)
target_sources(usermod_lv_bindings INTERFACE ${LV_SRC})
target_include_directories(usermod_lv_bindings INTERFACE ${LV_INCLUDE})
# BUG?? this fails to make usermod link to lvgl_interface
# even though INTERFACE libs should link transitively
if(0)
    # bindings depend on lvgl itself, pull it in
    include(${LVGL_DIR}/CMakeLists.txt)
    target_link_libraries(usermod_lv_bindings INTERFACE lvgl_interface)
else()
    # so for now just include the source directly, side-stepping lvgl/CMakeLists.txt
    file(GLOB_RECURSE LVGL_SRC ${CMAKE_CURRENT_LIST_DIR}/lvgl/src/*.c)
    target_sources(usermod_lv_bindings INTERFACE ${LVGL_SRC})
    target_compile_options(usermod_lv_bindings INTERFACE -Wno-unused-function)
endif()
# make usermod (target declared by Micropython for all user compiled modules) link to bindings
# this way the bindings (and transitively lvgl_interface) gets proper compilation flags etc
target_link_libraries(usermod INTERFACE usermod_lv_bindings)
```

Note the only unclear part is why `lvgl_interface` does not get linked to (so for now this is worked around in the `if(0)`). It is declared like this in `lvgl/CMakeLists.txt`:

```cmake
file(GLOB_RECURSE SOURCES ${CMAKE_CURRENT_LIST_DIR}/src/*.c)
add_library(lvgl_interface INTERFACE ${SOURCES})
```

Another issue is the `esp32` port, which is messing with Micropython's port `CMakeLists.txt`, something to be avoided. Those lines should be moved at the end of `lv_bindings/mkrules.cmake` (which is included via `USER_C_MODULES`) but I don't have resources to change/test that myself (no esp2 SDK here).

2021-09-03 20:52 UTC, amirgon commented on ports/rp2/CMakeLists.txt
> +file(GLOB_RECURSE MICROPY_SOURCE_LVGL ${MICROPY_DIR}/lib/lv_bindings/lvgl/src/*.c)
> Another issue is the `esp32` port, which is messing with Micropython's port `CMakeLists.txt`, something to be avoided. Those lines should be moved at the end of `lv_bindings/mkrules.cmake` (which is included via `USER_C_MODULES`) but I don't have resources to change/test that myself (no esp2 SDK here).

I can help testing the ESP32 port, when this is working for you.  
The ESP32 relies on [ESP-IDF Build-System infrastructure](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/build-system.html) which we would need to take into account.

We'll need to see if Micropython's external-modules support is flexible enough. For example, LVGL C code use Micropython's gc, the ESP32 port adds additional ESP-IDF SDK libraries etc. I'm not sure all this is supported for 3rd-party modules.
At least regarding gc, I know that [external modules don't support marking gc roots](https://github.com/micropython/micropython/pull/4195#issuecomment-460067965), but we may still be able to use external modules just for the build system.

Do you have any idea why `target_link_libraries` doesn't work for you?

2021-09-04 04:26 UTC, eudoxos commented on ports/rp2/CMakeLists.txt
> +file(GLOB_RECURSE MICROPY_SOURCE_LVGL ${MICROPY_DIR}/lib/lv_bindings/lvgl/src/*.c)
> Do you have any idea why target_link_libraries doesn't work for you?

No, unfortunately not yet.

The last commit is the least intrusive and most future-proof I could come up with:

1. upstream `mkconfigport.h` still needs to be updated with GC stuff (that one is beyond my understanding TBH), but `CMakeLists.txt` can be left as-is completely.
2. I added [lib/lv_bindings/bindings.cmake](https://github.com/lvgl/lv_binding_micropython/pull/174/files#diff-500d37457841984e82ba4a20b88746aebf845bedf7c46d642a763ba4a83ad854), to be used with `make USER_C_MODULES=../../lib/lv_bindings/bindings.cmake`. It has its internal issues with the INTERFACE target (and has to include LVGL sources directly), but this is hidden from the build process and can be improved in the future.
3. I did not touch any of esp32: I just added guards to `lv_bindings/mkrules.cmake`. I can see the lines added to micropython's `ports/esp32/CMakeLists.txt` go into `lv_bindings/bindings.cmake` under `if(ESP_PLATFORM)`. So again, only `mpconfigport.h` would be modified, and the esp32 build would use `USER_C_MODULES`.

The direction is that once (if) upstream solves the GC root for external modules, `lv_bindings` could build with upstream micropython.

2021-09-04 20:04 UTC, amirgon commented on ports/rp2/CMakeLists.txt
> +file(GLOB_RECURSE MICROPY_SOURCE_LVGL ${MICROPY_DIR}/lib/lv_bindings/lvgl/src/*.c)
> 1. upstream `mkconfigport.h` still needs to be updated with GC stuff (that one is beyond my understanding TBH), but `CMakeLists.txt` can be left as-is completely.

I think your `mkconfigport.h` already adds gc roots:
https://github.com/lvgl/lv_micropython/blob/ee9308b4e8521d7cc0e3c8b18172a011ccb74db4/ports/rp2/mpconfigport.h#L206-L208
Is anything missing there?

If `CMakeLists.txt` can be left as-is, please remove the white-space differences there.

> 2\. I added [lib/lv_bindings/bindings.cmake](https://github.com/lvgl/lv_binding_micropython/pull/174/files#diff-500d37457841984e82ba4a20b88746aebf845bedf7c46d642a763ba4a83ad854), to be used with `make USER_C_MODULES=../../lib/lv_bindings/bindings.cmake`

Is it ready to be merged? Is everything working on your side?
If it is, I'll take the time to check ESP32 with your changes.

> 3\. So again, only `mpconfigport.h` would be modified, and the esp32 build would use `USER_C_MODULES`.

Currently ESP32 builds LVGL as a library.  
As long as `target_link_libraries` doesn't work,  I'm not sure I would want a regression by using `USER_C_MODULES`.  

Furthermore, it's not clear to me how I can achieve this with user modules: there are in fact two CMake scripts that I've changed: [esp32/CMakeLists.txt](https://github.com/lvgl/lv_micropython/blob/master/ports/esp32/CMakeLists.txt) and [esp32/main/CMakeLists.txt](https://github.com/lvgl/lv_micropython/blob/master/ports/esp32/main/CMakeLists.txt). I needed to change both for ESP32 to build correctly.  
It's not clear how to keep both of these Cmake scripts unchanged but still add SDK libraries (`IDF_COMPONENTS`), register LVGL as a component, affect global definitions (`LV_KCONFIG_IGNORE`), etc.

> The direction is that once (if) upstream solves the GC root for external modules, `lv_bindings` could build with upstream micropython.

Unfortunately there are additional required changes in lv_micropython, so building with upstream micropython might not be that easy. These include changes to other ports (stm32, unix, windows, zephyr) but also global changes such as https://github.com/micropython/micropython/pull/6896 which was submitted many months ago but still haven't recieved any feedback from Micropython's maintainer.

2021-09-05 05:02 UTC, eudoxos commented on ports/rp2/CMakeLists.txt
> +file(GLOB_RECURSE MICROPY_SOURCE_LVGL ${MICROPY_DIR}/lib/lv_bindings/lvgl/src/*.c)
>> 1. upstream mkconfigport.h still needs to be updated with GC stuff
> I think your mkconfigport.h already adds gc roots:
Yes, I was just summarizing the future hypothetical state of upstream micropython build. This PR does include `LV_ROOTS`.

I removed the whitespace in CMakeLists.txt

> Is it ready to be merged? Is everything working on your side?
> If it is, I'll take the time to check ESP32 with your changes.

Yes, it is. `bindings.cmake` can't break ESP32 (not used at all) and `mkrules.cmake` was only adjusted with `if(ESP_PLATFORM)` around ESP32-specific things.  I appreciate your care about reliable ports.

>> Do you have any idea why target_link_libraries doesn't work for you?
> No, unfortunately not yet.

I figured it out now (see https://github.com/lvgl/lvgl/pull/2529 ; you will need that for testing), so now the interface target works as it should and bindings.cmake only link to `lvgl_interface`. Yay :)

The strange cmake trick was to use
```cmake
add_library(lvgl_interface INTERFACE)
target_sources(lvgl_interface INTERFACE ${SOURCES})
```
instead of `add_library(lvgl_interface INTERFACE ${SOURCES})` (where sources files were simply ignored).

2021-09-06 23:13 UTC, merged

2021-09-06 23:16 UTC, amirgon commented
Merged! Thank you.

I still need to bump `lv_bindings` for an updated version with https://github.com/lvgl/lv_binding_micropython/pull/174.
I will do that right after https://github.com/lvgl/lvgl/pull/2532 and https://github.com/lvgl/lv_micropython/pull/43 which hopefully would be merged soon.

2021-09-07 15:12 UTC, amirgon commented
> I still need to bump `lv_bindings` for an updated version with [lvgl/lv_binding_micropython#174](https://github.com/lvgl/lv_binding_micropython/pull/174).
> I will do that right after [lvgl/lvgl#2532](https://github.com/lvgl/lvgl/pull/2532) and #43 which hopefully would be merged soon.

Done.

2021-09-08 20:56 UTC, amirgon commented
@eudoxos - It could be useful to add a CI test for the rp2 port.  
Today we already have CI tests for the unix, esp32 and stm32 ports with GitHub Actions.
This would help to make sure we don't accidentally break this port in the future.